opam-version: "1.0"
maintainer: "Max Vistrup <contact@maxv.dk>"

synopsis: "Scaling reasoning about operational semantics using itrees."

depends: [
  "coq" { (>= "8.13" & < "8.18~") | (= "dev") }
  "coq-iris" { (= "dev.2023-08-11.1.81f394da") }
  "coq-itree" { (= "5.1.1") }
]

build: [make "-j%{jobs}%"]
install: [make "install"]
