opam-version: "1.0"
maintainer: "Max Vistrup <contact@maxv.dk>"

synopsis: "Scaling reasoning about operational semantics using itrees."

depends: [
  "coq-iris-heap-lang" { (= "dev.2024-02-16.1.06f499e0") | (= "dev") }
  "coq-iris" { (= "dev.2024-02-16.1.06f499e0") | (= "dev") }
  "coq-itree" { (= "5.1.2") }
  "coq-elpi" { (= "2.0.1") }
  "coq-stdpp-unstable"
  "coq-record-update"
]

build: [make "-j%{jobs}%"]
install: [make "install"]
